# Generated by Django 3.0.7 on 2020-06-26 09:55

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('storage', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='label',
            old_name='étiquette',
            new_name='etiquette',
        ),
        migrations.CreateModel(
            name='Photo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('photo', models.ImageField(upload_to='photos/')),
                ('date', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Date ajout')),
                ('categorie', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='storage.Label')),
            ],
            options={
                'ordering': ['date'],
            },
        ),
    ]
